import type { Metadata } from 'next';
import { Kantumruy_Pro } from 'next/font/google';
import '../globals.css';
import Footer from '@/components/footer/Index';

import { NavBar } from '@/components/navbar/navbar';
import { NextIntlClientProvider, useMessages } from 'next-intl';

const kantumruy_pro = Kantumruy_Pro({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
    params: { locale },
}: Readonly<{
    children: React.ReactNode;
    params: { locale: string };
}>) {
    const messages = useMessages();
    return (
        <html lang={locale}>

            <head>
                <link rel='icon' href='/favicon.ico' sizes='any' />
            </head>
            <body className={kantumruy_pro.className}>
                <NextIntlClientProvider messages={messages}>
                    <NavBar />
                    {children}
                    <Footer />
                </NextIntlClientProvider>
            </body>
        </html>
    );
}
